language: java
after_success:
  # CREATE GIT TAG 
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-B$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$KEY@github.com/codydbgt/BasicBukkitPlugin $GIT_TAG > /dev/null 2>&1
deploy:
  provider: releases
  api_key: $KEY
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/target/*.jar
  skip_cleanup: true
  on:
    tags: false
branches:
  except:
    - /^build-[0-9a-z\-]*/